# Factor Rotation Methods - MA2003B Multivariate Statistics Course

This notebook demonstrates factor rotation techniques in Factor Analysis. Rotation improves interpretability by transforming the factor solution to achieve "simple structure" where variables load highly on few factors and factors are clearly distinct.

## Learning Objectives:
- Understand the purpose of factor rotation
- Compare orthogonal (Varimax) vs oblique (Promax) rotation
- See how rotation affects factor loadings and interpretability
- Recognize when rotation improves factor structure

**Data**: Simulated 100 observations × 3 variables to demonstrate rotation effects

**Expected Output**:
- Comparison of loadings before and after rotation
- Demonstration of how rotation clarifies factor structure

In [1]:
# Import Required Libraries
import numpy as np
from factor_analyzer import FactorAnalyzer

In [2]:
# Generate Sample Data
# Using 3 variables to show clear rotation effects on 2 factors
np.random.seed(42)
X = np.random.randn(100, 3)

In [3]:
# Display Dataset Information
print("Factor Rotation Comparison")
print("=" * 40)
print(f"Dataset: {X.shape[0]} observations × {X.shape[1]} variables")
print("Extracting 2 factors with different rotation methods")

Factor Rotation Comparison
Dataset: 100 observations × 3 variables
Extracting 2 factors with different rotation methods


In [4]:
# Method 1: No Rotation (Raw Factor Solution)
# This gives the initial, often uninterpretable solution
fa_no_rotation = FactorAnalyzer(n_factors=2, method="principal")
fa_no_rotation.fit(X)

loadings_before = fa_no_rotation.loadings_

print("1. Unrotated Factor Solution:")
print("   Raw loadings - may be difficult to interpret")
print("   Factors are orthogonal but not necessarily meaningful")
print(loadings_before.round(3))

1. Unrotated Factor Solution:
   Raw loadings - may be difficult to interpret
   Factors are orthogonal but not necessarily meaningful
[[-0.229  0.892]
 [ 0.885 -0.252]
 [-0.541 -0.514]]


/home/julihocc/ma2003b/ma2003b.worktrees/dev/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [5]:
# Method 2: Varimax Rotation (Orthogonal)
# Maximizes variance of squared loadings within factors
# Maintains factor independence (orthogonal factors)
fa_varimax = FactorAnalyzer(n_factors=2, rotation="varimax", method="principal")
fa_varimax.fit(X)

loadings_varimax = fa_varimax.loadings_

print("2. Varimax Rotation (Orthogonal):")
print("   Simplifies factor structure while keeping factors uncorrelated")
print("   Each variable loads highly on one factor, minimally on others")
print(loadings_varimax.round(3))

2. Varimax Rotation (Orthogonal):
   Simplifies factor structure while keeping factors uncorrelated
   Each variable loads highly on one factor, minimally on others
[[-0.148  0.868]
 [ 0.86  -0.172]
 [-0.585 -0.56 ]]


/home/julihocc/ma2003b/ma2003b.worktrees/dev/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [6]:
# Method 3: Promax Rotation (Oblique)
# Oblique rotation allowing factors to correlate
# Often more realistic as psychological constructs are related
fa_promax = FactorAnalyzer(n_factors=2, rotation="promax", method="principal")
fa_promax.fit(X)

loadings_promax = fa_promax.loadings_

print("3. Promax Rotation (Oblique):")
print("   Allows factors to correlate, which is often more realistic")
print("   May provide cleaner simple structure than orthogonal rotation")
print(loadings_promax.round(3))

3. Promax Rotation (Oblique):
   Allows factors to correlate, which is often more realistic
   May provide cleaner simple structure than orthogonal rotation
[[-0.229  0.892]
 [ 0.885 -0.252]
 [-0.541 -0.514]]


/home/julihocc/ma2003b/ma2003b.worktrees/dev/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [7]:
# Additional rotation options available:
# - 'oblimin': Alternative oblique rotation
# - 'quartimax': Alternative orthogonal rotation
# - None: No rotation (default)

## Rotation Comparison Summary

- **Unrotated**: Mathematically optimal but often uninterpretable
- **Varimax**: Simplifies structure, maintains orthogonality (factors uncorrelated)
- **Promax**: Allows correlation between factors, often clearest interpretation
- **Choose based on theoretical expectations** about whether factors should be independent

## Key Insights

- **Rotation doesn't change the overall fit**, only the factor orientation in the variable space
- **Goal is to achieve 'simple structure'** for better interpretability
- **Orthogonal vs oblique** depends on whether factors should theoretically be independent
- **Always compare rotated solutions** to ensure the chosen rotation improves interpretability